[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.17.0"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"
